services:
  # 1. Database - PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: truyenkomi-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=TruyenKomiDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TruyenKomiDbPassword2026!
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d:ro

  # 2. Cache - Redis
  redis:
    image: redis:7-alpine
    container_name: truyenkomi-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

  # 3. Search Engine - Meilisearch
  meilisearch:
    image: getmeili/meilisearch:v1.10
    container_name: truyenkomi-meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=TruyenKomiMeiliMasterKey2026!
      - MEILI_ENV=production
      - MEILI_NO_ANALYTICS=true
    restart: always
    volumes:
      - meili_data:/meili_data

  # 4. Backend .NET Web API
  api:
    build:
      context: ./backend/MangaFlux.API
      dockerfile: Dockerfile
    container_name: truyenkomi-api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_CONNECTION_STRING=Host=postgres;Port=5432;Database=TruyenKomiDb;Username=postgres;Password=TruyenKomiDbPassword2026!;
      - REDIS_CONNECTION_STRING=redis:6379,abortConnect=false
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILI_MASTER_KEY=TruyenKomiMeiliMasterKey2026!
      - JWT_SECRET=${JWT_SECRET:-TruyenKomiSecretKeyForJwtTokenGeneration2026SuperSecure!}
      - JWT_ISSUER=${JWT_ISSUER:-TruyenKomiAPI}
      - JWT_AUDIENCE=${JWT_AUDIENCE:-TruyenKomiClient}
      - JWT_EXPIRY_DAYS=${JWT_EXPIRY_DAYS:-7}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-510177815251-88f3mqoiatfct4jj0bhnuhmol985ae0s.apps.googleusercontent.com}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-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}
      - R2_ENDPOINT=${R2_ENDPOINT:-storage.googleapis.com}
      - R2_ACCESS_KEY=${R2_ACCESS_KEY:-GOOGQHRXVRS7YCR24JBLB33S}
      - R2_SECRET_KEY=${R2_SECRET_KEY:-3Iamo8whmuUeT2B+CMtRnfW6qdIsmwXVec47tF52}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME:-truyenkomi}
      - R2_SECURE=${R2_SECURE:-true}
      - R2_CDN_BASE_URL=${R2_CDN_BASE_URL:-https://img.truyenkomi.site}
    depends_on:
      - postgres
      - redis
      - meilisearch

  # 5. Frontend Angular SPA
  frontend:
    build:
      context: ./angular
      dockerfile: Dockerfile
    container_name: truyenkomi-frontend
    restart: always
    ports:
      - "4200:80"

  # 6. Gateway / Reverse Proxy - Nginx
  nginx:
    image: nginx:alpine
    container_name: truyenkomi-nginx
    ports:
      - "80:80"
      - "8080:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - frontend
      - redis

volumes:
  postgres_data:
  redis_data:
  meili_data:
